---

- name: Register baremetal nodes
  hosts: controllers[0]
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
  tasks:
    - name: Set up openstack cli virtualenv
      pip:
        virtualenv: "{{ venv }}"
        name:
          - python-openstackclient
          - python-ironicclient
        state: latest
        virtualenv_command: "python3.{{ ansible_facts.python.version.minor }} -m venv"
        extra_args: "{% if pip_upper_constraints_file %}-c {{ pip_upper_constraints_file }}{% endif %}"

- name: Ensure baremetal nodes are registered in ironic
  hosts: baremetal
  gather_facts: false
  max_fail_percentage: >-
    {{ baremetal_register_max_fail_percentage |
       default(baremetal_max_fail_percentage) |
       default(kayobe_max_fail_percentage) |
       default(100) }}
  tags:
    - baremetal
  vars:
    venv: "{{ virtualenv_path }}/openstack-cli"
    controller_host: "{{ groups['controllers'][0] }}"
  tasks:
    - name: Enroll baremetal nodes in Ironic
      openstack.cloud.baremetal_node:
        auth_type: "{{ openstack_auth_type }}"
        auth: "{{ openstack_auth }}"
        bios_interface: "{{ baremetal_bios_interface }}"
        boot_interface: "{{ baremetal_boot_interface }}"
        ca_cert: "{{ openstack_cacert | default(omit, true) }}"
        chassis_id: "{{ baremetal_chassis_id }}"
        console_interface: "{{ baremetal_console_interface }}"
        deploy_interface: "{{ baremetal_deploy_interface }}"
        driver: "{{ baremetal_driver }}"
        driver_info: "{{ baremetal_driver_info }}"
        id: "{{ baremetal_uuid | default(omit) }}"
        inspect_interface: "{{ baremetal_inspect_interface }}"
        interface: "{{ openstack_interface | default(omit, true) }}"
        management_interface: "{{ baremetal_management_interface }}"
        name: "{{ inventory_hostname }}"
        network_interface: "{{ baremetal_network_interface }}"
        power_interface: "{{ baremetal_power_interface }}"
        properties: "{{ baremetal_properties }}"
        make_available_on_node_create: false
        raid_interface: "{{ baremetal_raid_interface }}"
        rescue_interface: "{{ baremetal_rescue_interface }}"
        resource_class: "{{ baremetal_resource_class }}"
        storage_interface: "{{ baremetal_storage_interface }}"
        timeout: "{{ baremetal_timeout }}"
        vendor_interface: "{{ baremetal_vendor_interface }}"
        wait: "{{ baremetal_wait }}"
      delegate_to: "{{ controller_host }}"
      vars:
        # NOTE: Without this, the controller's ansible_host variable will not
        # be respected when using delegate_to.
        ansible_host: "{{ hostvars[controller_host].ansible_host | default(controller_host) }}"
        ansible_python_interpreter: "{{ venv }}/bin/python3"
